yolov6/core/engine.py

Fix typo for feature pre-commit

Fix typo for feature pre-commit

---

README.md

currently, the single gpu training, the batch size 256 is too large. We should change it to 32.

in readme file, single gpu training, the batchsize should be 32

---

yolov6/data/datasets.py

exchange the `img_w` and `img_h` in `generate_coco_format_labels`, cause the previously saved size(shape = im.size) in `check_image` is (width, height) format, not (height, width) format. also I added some code formatting.

fix convert coco format bug

---

docs/Train_custom_data.md
tools/eval.py

Remove unnecessary space in bracket

Remove space in bracket

---

README.md

https://mp.weixin.qq.com/s/oxWodmYtULp5KznSYI19wQ
接下来我们会对 TRT_EfficientNMS plugin 做支持, 并提供 DLL C# 动态调用接口

Add third party TensorRT Windows C++ support

---

tools/eval.py

Fix the bug that increasing exp name in training mode.

Fix exp name increase bug

---

yolov6/models/end2end.py

yolov6/models/end2end.py ： [modify torch.concat() to torch.cat()](https://github.com/meituan/YOLOv6/blob/main/yolov6/models/end2end.py#:~:text=return%20torch.concat(%5BX%2C%20resBoxes%2C%20resClasses%2C%20resScores%5D%2C%201))

modify torch.concat() to torch.cat()

---

yolov6/data/voc2yolo.py

Add `gen_voc07_12` function, automatically generate `voc07+12` dataset when converting voc dataset to yolo format.

Add gen_voc07_12 function

---

tools/infer.py

Added a check in infer .py to make sure that save_txt path already does not exists

Added save txt path already exists or not check in infer.py

---

.gitignore
deploy/ONNX/export_onnx.py
yolov6/models/end2end.py

standardize the codes of end2end onnx export.

standardize the codes of end2end onnx export

---

tools/infer.py

standardize the comment in tools/infer.py

standardize the comment

---

README.md

This PR adds a link to a in browser demo that folks can try out without having to run the code themselves. Check it out here: [![Hugging Face Spaces](https://img.shields.io/badge/%F0%9F%A4%97%20Hugging%20Face-Spaces-blue)](https://huggingface.co/spaces/nateraw/yolov6)
If there's anything I can add to this demo (more links to your site/research) let me know!

Add huggingface spaces demo to readme

---

deploy/ONNX/export_onnx.py

🐛 Fix the bug of specifying device. It only worked on device cuda:0 through you set `--device 1`. 
Now it could work normally :).

Fix the bug of gpu device specified

---

docs/Train_custom_data.md

Train_custom_data.md visual improvement and typo fix.

Train_custom_data.md improvement and typo fix

---

tools/train.py
yolov6/core/engine.py
yolov6/utils/events.py

Add learning rate to tensorboard and adjust tensorboard batch_image write setting.

Add learning rate to tensorboard and adjust tensorboard batch_image write setting

---

yolov6/data/datasets.py

Fix the bug in dataset.py causing an error when training with images of .tif formats

Fix the '_getexif' bug in dataset.py

---

tools/partial_quantization/ptq.py

device parameter was not passed to collect_stats in ptq/do_ptq

In ptq.do_ptq

---

yolov6/core/engine.py

Change the strip model logic to solve the problem of resume.

change the strip model logic to solve the problem of resume.

---

configs/repopt/yolov6_tiny_hs.py
configs/repopt/yolov6_tiny_opt.py
configs/repopt/yolov6_tiny_opt_qat.py
configs/repopt/yolov6n_hs.py
configs/repopt/yolov6n_opt.py
configs/repopt/yolov6n_opt_qat.py
tools/qat/qat_export.py
yolov6/models/reppan.py

2. add tiny and nano qat configs

1. fix bug of qat

---

tools/eval.py
yolov6/core/evaler.py
yolov6/data/datasets.py

Add 'test' task to `eval.py` to evaluate using 'test' set for custom dataset.

Add task 'test' to eval scripts

---

yolov6/core/inferer.py

feat: put utf-8 text

---

README.md
README_cn.md

Add chinese version readme document.

Add chinese version readme document.

---

docs/Tutorial of Quantization.md
tools/quantization/ppq/ProgramEntrance.py
tools/quantization/ppq/write_qparams_onnx2trt.py

* Upload PPQ Quantization Sample for TensorRT
* Modify Quantization Tutorial.md

Upload PPQ Quantization Sample

---

deploy/ONNX/OpenCV/yolo_video.py

Decided to make a little contribution by using ideas from the yolo.py file to make real-time predictions using any video source.
sample usage
```
python yolo_video.py --model "./yolov6n.onnx" --source 0
```

added video object detector with opencv

---

README.md
README_cn.md
yolov6/models/loss.py
yolov6/models/loss_distill.py

fix the bug that will cause classification loss to be inf.

fix the bug that will cause classification loss to be inf.

---

tools/infer.py

fix the logical problem in infer argparse parameter.

fix the logical problem in infer argparse parameter.

---

deploy/TensorRT/Processor.py
deploy/TensorRT/eval_yolo_trt.py
tools/qat/qat_export.py

Fix the bug of visualization in tensorrt inference .

Fix the bug of visualization in tensorrt inference 

---

README.md

I have added a blog post that explains the YOLOv6 paper, and model architecture and discusses the results. It also runs inference on videos while drawing comparisons between YOLOv7 and YOLOv5.
It will help everyone get a better understanding of YOLOv6 and how it is better compared to the other architecture.

YOLOv6 Object Detection – Paper Explanation and Inference blog post added to Third-Party resource

---

docs/Train_custom_data.md

Hi 👋! I would like to ask if you would consider adding Roboflow as one of the suggested tools in the "Prepare your own dataset" section".
- Roboflow is [free](https://roboflow.com/pricing) to use for open-source projects.
- We support dataset export in a fully YOLOv6-compatible format. We even call it `meituan/YOLOv6`.
- We are actively supporting the open-source CV community. YOLOv5 recommends us for data labeling.

Add Roboflow as proposed labeling tool

---

tools/train.py

https://github.com/meituan/YOLOv6/issues/640

fix rank typo

---

yolov6/models/loss.py
yolov6/models/loss_distill.py

Change loss normalization logic, the `target_scores_sum` may be very small, if loss divided by a very small number, it will be very big and chance to be NAN.

change the loss normalization logic to avoid loss to be nan.

---

configs/repopt/yolov6_tiny_hs.py
configs/repopt/yolov6_tiny_opt.py
configs/repopt/yolov6_tiny_opt_qat.py
configs/repopt/yolov6n_hs.py
configs/repopt/yolov6n_opt.py
configs/repopt/yolov6n_opt_qat.py
configs/repopt/yolov6s_hs.py
configs/repopt/yolov6s_opt.py
configs/repopt/yolov6s_opt_qat.py
configs/yolov6n.py

Fix bug of training V6-RepOpt: no attribute 'atss_warmup_epoch'

---

yolov6/core/engine.py
yolov6/core/evaler.py
yolov6/layers/common.py
yolov6/utils/general.py

Add function of model automatically download from github.

Model automatically download from GitHub

---

yolov6/layers/common.py
yolov6/utils/general.py

Code is formatted using black and isort

feat  auto download checkpoint

---

turtorial.ipynb

Fix typo in turtorial.ipynb

---

docs/Train_custom_data.md

Update commands of model export

Update commands of model export

---

tools/eval.py

The word evaluation is misspelled.

The word evaluation is misspelled.

---

yolov6/core/engine.py

fix confusing compution of evaluation epochs.

fix confusing compution of evaluation epochs.

---

configs/qarepvgg/yolov6m_qa.py
configs/qarepvgg/yolov6n_qa.py
configs/qarepvgg/yolov6s_qa.py
yolov6/layers/common.py

Add QARepVGG V2

---

configs/experiment/eval_640_repro.py
configs/mbla/README.md
configs/mbla/README_cn.md
configs/mbla/yolov6l_mbla.py
configs/mbla/yolov6l_mbla_finetune.py
configs/mbla/yolov6m_mbla.py
configs/mbla/yolov6m_mbla_finetune.py
configs/mbla/yolov6s_mbla.py
configs/mbla/yolov6s_mbla_finetune.py
configs/mbla/yolov6x_mbla.py
configs/mbla/yolov6x_mbla_finetune.py
yolov6/layers/common.py
yolov6/models/efficientrep.py
yolov6/models/reppan.py
yolov6/models/yolo.py

Apply MBLABlock(Multi Branch Layer Aggregation Block) blocks in the network structure.
Adopt a unified network structure and configuration.
Better performance for Small model comparing to yolov6 3.0 release.

add mbla block version

---

hubconf.py

fix the error of rgb to bgr order convert.

Fix preprocess bug in hubconf

---

deploy/ONNX/export_onnx.py
deploy/OpenVINO/export_openvino.py
yolov6/core/evaler.py

Fix upsample bug

---

yolov6/core/inferer.py

Fix infer Upsample bug

---

deploy/NCNN/export_torchscript.py
yolov6/models/effidehead.py
yolov6/models/heads/effidehead_distill_ns.py
yolov6/models/heads/effidehead_fuseab.py
yolov6/models/heads/effidehead_lite.py
yolov6/models/yolo.py
yolov6/models/yolo_lite.py

Support YOLOv6 lite model ncnn deploy

Support YOLOv6 lite model ncnn deploy

---

deploy/NCNN/README.md
deploy/NCNN/infer-lite-model.py
deploy/NCNN/infer-ncnn-model.py

Add python inference script and README

Add python inference script and README

---

configs/yolov6_lite/yolov6_lite_l_finetune.py
configs/yolov6_lite/yolov6_lite_m_finetune.py
configs/yolov6_lite/yolov6_lite_s_finetune.py

Hi 
Yolov6 lite pretraind model has a different name!
I updated it the same as the mobile Vanchmark model name that I am currently distributing.

Update lite model names

---

README.md

Hi Team, I have built a Tutorial which guides on training yolov6 with custom container/bring your own algorithm for Sagemaker Training. Thanks.

Added Third party resource for sagemaker training

---

yolov6/models/losses/loss.py

Fix the confict of  branch about cache anchors feature by triplemu.

Triple mu triplemu/cached anchors
